export const Jobs =[
    {
        jobId: '1',
        jobTitle: 'Senior Software Engineer',
        location: 'New York, NY',
        jobCreationDate: '2025-09-01',
        jobSalary: '$120,000 - $150,000',
        jobType: 'Full-time',
        jobRoles: ['Develop and maintain web applications.', 'Collaborate with product teams.', 'Mentor junior developers.'],
        jobDescription: 'Seeking a skilled Senior Software Engineer with a passion for building scalable web applications. Must have experience with React and Node.js.',
        noOfCandidatesApplied: 15,
        jobDeadline: '2025-10-31',
        jobAssessmentQuestions: ['What is a closure in JavaScript?', 'Describe your experience with RESTful APIs.'],
        jobEligibility: ['5+ years of experience', 'B.S. in Computer Science or equivalent'],
        status: 'Active',
    },
    {
        jobId: '2',
        jobTitle: 'Product Manager',
        location: 'San Francisco, CA',
        jobCreationDate: '2025-08-25',
        jobSalary: '$130,000 - $160,000',
        jobType: 'Full-time',
        jobRoles: ['Define product vision and strategy.', 'Work with engineering teams to build products.'],
        jobDescription: 'We are looking for a visionary Product Manager to lead our next-gen product line. Strong communication and leadership skills are a must.',
        noOfCandidatesApplied: 8,
        jobDeadline: '2025-11-15',
        jobAssessmentQuestions: ['How do you prioritize features?', 'Tell me about a time you launched a product.'],
        jobEligibility: ['7+ years of product management', 'Experience with Agile methodologies'],
        status: 'Closed',
    },
    {
        jobId: '3',
        jobTitle: 'Data Scientist',
        location: 'Remote',
        jobCreationDate: '2025-09-10',
        jobSalary: '$110,000 - $140,000',
        jobType: 'Full-time',
        jobRoles: ['Analyze large datasets to identify trends.', 'Build machine learning models.', 'Present findings to stakeholders.'],
        jobDescription: 'Passionate data scientist needed to join our analytics team. Must be proficient in Python and machine learning frameworks.',
        noOfCandidatesApplied: 25,
        jobDeadline: '2025-10-20',
        jobAssessmentQuestions: ['Explain the difference between supervised and unsupervised learning.', 'What is your favorite ML model and why?'],
        jobEligibility: ['3+ years of experience', 'M.S. in a quantitative field'],
        status: 'Active',
    },
    {
        jobId: '1',
        jobTitle: 'Senior Software Engineer',
        location: 'New York, NY',
        jobCreationDate: '2025-09-01',
        jobSalary: '$120,000 - $150,000',
        jobType: 'Full-time',
        jobRoles: ['Develop and maintain web applications.', 'Collaborate with product teams.', 'Mentor junior developers.'],
        jobDescription: 'Seeking a skilled Senior Software Engineer with a passion for building scalable web applications. Must have experience with React and Node.js.',
        noOfCandidatesApplied: 15,
        jobDeadline: '2025-10-31',
        jobAssessmentQuestions: ['What is a closure in JavaScript?', 'Describe your experience with RESTful APIs.'],
        jobEligibility: ['5+ years of experience', 'B.S. in Computer Science or equivalent'],
        status: 'Active',
    },
    {
        jobId: '2',
        jobTitle: 'Product Manager',
        location: 'San Francisco, CA',
        jobCreationDate: '2025-08-25',
        jobSalary: '$130,000 - $160,000',
        jobType: 'Full-time',
        jobRoles: ['Define product vision and strategy.', 'Work with engineering teams to build products.'],
        jobDescription: 'We are looking for a visionary Product Manager to lead our next-gen product line. Strong communication and leadership skills are a must.',
        noOfCandidatesApplied: 8,
        jobDeadline: '2025-11-15',
        jobAssessmentQuestions: ['How do you prioritize features?', 'Tell me about a time you launched a product.'],
        jobEligibility: ['7+ years of product management', 'Experience with Agile methodologies'],
        status: 'Closed',
    },
    {
        jobId: '3',
        jobTitle: 'Data Scientist',
        location: 'Remote',
        jobCreationDate: '2025-09-10',
        jobSalary: '$110,000 - $140,000',
        jobType: 'Full-time',
        jobRoles: ['Analyze large datasets to identify trends.', 'Build machine learning models.', 'Present findings to stakeholders.'],
        jobDescription: 'Passionate data scientist needed to join our analytics team. Must be proficient in Python and machine learning frameworks.',
        noOfCandidatesApplied: 25,
        jobDeadline: '2025-10-20',
        jobAssessmentQuestions: ['Explain the difference between supervised and unsupervised learning.', 'What is your favorite ML model and why?'],
        jobEligibility: ['3+ years of experience', 'M.S. in a quantitative field'],
        status: 'Active',
    },
    {
        jobId: '1',
        jobTitle: 'Senior Software Engineer',
        location: 'New York, NY',
        jobCreationDate: '2025-09-01',
        jobSalary: '$120,000 - $150,000',
        jobType: 'Full-time',
        jobRoles: ['Develop and maintain web applications.', 'Collaborate with product teams.', 'Mentor junior developers.'],
        jobDescription: 'Seeking a skilled Senior Software Engineer with a passion for building scalable web applications. Must have experience with React and Node.js.',
        noOfCandidatesApplied: 15,
        jobDeadline: '2025-10-31',
        jobAssessmentQuestions: ['What is a closure in JavaScript?', 'Describe your experience with RESTful APIs.'],
        jobEligibility: ['5+ years of experience', 'B.S. in Computer Science or equivalent'],
        status: 'Active',
    },
    {
        jobId: '2',
        jobTitle: 'Product Manager',
        location: 'San Francisco, CA',
        jobCreationDate: '2025-08-25',
        jobSalary: '$130,000 - $160,000',
        jobType: 'Full-time',
        jobRoles: ['Define product vision and strategy.', 'Work with engineering teams to build products.'],
        jobDescription: 'We are looking for a visionary Product Manager to lead our next-gen product line. Strong communication and leadership skills are a must.',
        noOfCandidatesApplied: 8,
        jobDeadline: '2025-11-15',
        jobAssessmentQuestions: ['How do you prioritize features?', 'Tell me about a time you launched a product.'],
        jobEligibility: ['7+ years of product management', 'Experience with Agile methodologies'],
        status: 'Closed',
    },
    {
        jobId: '3',
        jobTitle: 'Data Scientist',
        location: 'Remote',
        jobCreationDate: '2025-09-10',
        jobSalary: '$110,000 - $140,000',
        jobType: 'Full-time',
        jobRoles: ['Analyze large datasets to identify trends.', 'Build machine learning models.', 'Present findings to stakeholders.'],
        jobDescription: 'Passionate data scientist needed to join our analytics team. Must be proficient in Python and machine learning frameworks.',
        noOfCandidatesApplied: 25,
        jobDeadline: '2025-10-20',
        jobAssessmentQuestions: ['Explain the difference between supervised and unsupervised learning.', 'What is your favorite ML model and why?'],
        jobEligibility: ['3+ years of experience', 'M.S. in a quantitative field'],
        status: 'Active',
    },
    {
        jobId: '1',
        jobTitle: 'Senior Software Engineer',
        location: 'New York, NY',
        jobCreationDate: '2025-09-01',
        jobSalary: '$120,000 - $150,000',
        jobType: 'Full-time',
        jobRoles: ['Develop and maintain web applications.', 'Collaborate with product teams.', 'Mentor junior developers.'],
        jobDescription: 'Seeking a skilled Senior Software Engineer with a passion for building scalable web applications. Must have experience with React and Node.js.',
        noOfCandidatesApplied: 15,
        jobDeadline: '2025-10-31',
        jobAssessmentQuestions: ['What is a closure in JavaScript?', 'Describe your experience with RESTful APIs.'],
        jobEligibility: ['5+ years of experience', 'B.S. in Computer Science or equivalent'],
        status: 'Active',
    },
    {
        jobId: '2',
        jobTitle: 'Product Manager',
        location: 'San Francisco, CA',
        jobCreationDate: '2025-08-25',
        jobSalary: '$130,000 - $160,000',
        jobType: 'Full-time',
        jobRoles: ['Define product vision and strategy.', 'Work with engineering teams to build products.'],
        jobDescription: 'We are looking for a visionary Product Manager to lead our next-gen product line. Strong communication and leadership skills are a must.',
        noOfCandidatesApplied: 8,
        jobDeadline: '2025-11-15',
        jobAssessmentQuestions: ['How do you prioritize features?', 'Tell me about a time you launched a product.'],
        jobEligibility: ['7+ years of product management', 'Experience with Agile methodologies'],
        status: 'Closed',
    },
    {
        jobId: '3',
        jobTitle: 'Data Scientist',
        location: 'Remote',
        jobCreationDate: '2025-09-10',
        jobSalary: '$110,000 - $140,000',
        jobType: 'Full-time',
        jobRoles: ['Analyze large datasets to identify trends.', 'Build machine learning models.', 'Present findings to stakeholders.'],
        jobDescription: 'Passionate data scientist needed to join our analytics team. Must be proficient in Python and machine learning frameworks.',
        noOfCandidatesApplied: 25,
        jobDeadline: '2025-10-20',
        jobAssessmentQuestions: ['Explain the difference between supervised and unsupervised learning.', 'What is your favorite ML model and why?'],
        jobEligibility: ['3+ years of experience', 'M.S. in a quantitative field'],
        status: 'Active',
    },
    // Add more jobs here to test pagination
];
